version: "3.3"

services:
  redis-stats:
    container_name: redis-stats
    image: l33tlamer/redis-stats
    restart: unless-stopped
    ### map port 8080 to whichever host port you like:
    ports:
      - 7734:8080
    ### use either env vars for a single Redis instance:
    environment:
      - "REDIS_NAME=My Redis"
      - "REDIS_HOST=192.168.20.50"
      - "REDIS_PORT=6379"
    ### OR supply config file for multiple instances:
    volumes:
      - ./config.php:/var/www/html/config.php
